apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3  # Name the new StorageClass as 'gp3'
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"  # Optional: make it the default StorageClass
provisioner: ebs.csi.eks.amazonaws.com
reclaimPolicy: Retain
# volumeBindingMode: WaitForFirstConsumer
volumeBindingMode: Immediate
parameters:
  type: gp3  # Use 'gp3' type instead of 'gp2'
allowedTopologies:
- matchLabelExpressions:
  - key: topology.ebs.csi.aws.com/zone
    values:
    - us-east-2a  # Replace with your cluster's AZ
