apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-pv
spec:
  capacity:
    storage: 25Gi   # Adjust the storage size as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce   # Only one pod can mount the volume
  persistentVolumeReclaimPolicy: Retain  # Options: Retain, Recycle, Delete
  storageClassName: "gp3"  # Default StorageClass (empty means the default one is used)
  awsElasticBlockStore:
    volumeID: vol-02e6c2e101f58d1b9  # Replace with your actual volume ID
    fsType: ext4  # Adjust filesystem type (e.g., ext4, xfs)
